package io.github.kdroidfilter.seforimapp.catalog

import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlin.collections.Map

public data class BookRef(
  public val id: Long,
  public val title: String,
)

public data class TocQuickLink(
  public val label: String,
  public val tocEntryId: Long,
  public val firstLineId: Long?,
)

public object PrecomputedCatalog {
  public val BOOK_TITLES: Map<Long, String> = mapOf(
        1L to "בראשית",
        2L to "שמות",
        3L to "ויקרא",
        4L to "במדבר",
        5L to "דברים",
        6L to "יהושע",
        7L to "שופטים",
        8L to "שמואל א",
        9L to "שמואל ב",
        10L to "מלכים א",
        11L to "מלכים ב",
        12L to "ישעיהו",
        13L to "ירמיהו",
        14L to "יחזקאל",
        15L to "הושע",
        16L to "יואל",
        17L to "עמוס",
        18L to "עובדיה",
        19L to "יונה",
        20L to "מיכה",
        21L to "נחום",
        22L to "חבקוק",
        23L to "צפניה",
        24L to "חגי",
        25L to "זכריה",
        26L to "מלאכי",
        27L to "רות",
        28L to "תהילים",
        29L to "איוב",
        30L to "משלי",
        31L to "שיר השירים",
        32L to "קהלת",
        33L to "איכה",
        34L to "אסתר",
        35L to "דניאל",
        36L to "עזרא",
        37L to "נחמיה",
        38L to "דברי הימים א",
        39L to "דברי הימים ב",
        40L to "משנה ברכות",
        41L to "משנה פאה",
        42L to "משנה דמאי",
        43L to "משנה כלאים",
        44L to "משנה שביעית",
        45L to "משנה תרומות",
        46L to "משנה מעשרות",
        47L to "משנה מעשר שני",
        48L to "משנה חלה",
        49L to "משנה ערלה",
        50L to "משנה ביכורים",
        51L to "משנה שבת",
        52L to "משנה עירובין",
        53L to "משנה פסחים",
        54L to "משנה שקלים",
        55L to "משנה יומא",
        56L to "משנה סוכה",
        57L to "משנה ביצה",
        58L to "משנה ראש השנה",
        59L to "משנה תענית",
        60L to "משנה מגילה",
        61L to "משנה מועד קטן",
        62L to "משנה חגיגה",
        63L to "משנה יבמות",
        64L to "משנה כתובות",
        65L to "משנה נדרים",
        66L to "משנה נזיר",
        67L to "משנה סוטה",
        68L to "משנה גיטין",
        69L to "משנה קידושין",
        70L to "משנה בבא קמא",
        71L to "משנה בבא מציעא",
        72L to "משנה בבא בתרא",
        73L to "משנה סנהדרין",
        74L to "משנה מכות",
        75L to "משנה שבועות",
        76L to "משנה עדיות",
        77L to "משנה עבודה זרה",
        78L to "משנה אבות",
        79L to "משנה הוריות",
        80L to "משנה זבחים",
        81L to "משנה מנחות",
        82L to "משנה חולין",
        83L to "משנה בכורות",
        84L to "משנה ערכין",
        85L to "משנה תמורה",
        86L to "משנה כריתות",
        87L to "משנה מעילה",
        88L to "משנה תמיד",
        89L to "משנה מדות",
        90L to "משנה קינים",
        91L to "משנה כלים",
        92L to "משנה אהלות",
        93L to "משנה נגעים",
        94L to "משנה פרה",
        95L to "משנה טהרות",
        96L to "משנה מקואות",
        97L to "משנה נדה",
        98L to "משנה מכשירין",
        99L to "משנה זבים",
        100L to "משנה טבול יום",
        101L to "משנה ידים",
        102L to "משנה עוקצים",
        103L to "ברכות",
        104L to "שבת",
        105L to "עירובין",
        106L to "פסחים",
        107L to "יומא",
        108L to "סוכה",
        109L to "ביצה",
        110L to "ראש השנה",
        111L to "תענית",
        112L to "מגילה",
        113L to "מועד קטן",
        114L to "חגיגה",
        115L to "יבמות",
        116L to "כתובות",
        117L to "נדרים",
        118L to "נזיר",
        119L to "סוטה",
        120L to "גיטין",
        121L to "קידושין",
        122L to "בבא קמא",
        123L to "בבא מציעא",
        124L to "בבא בתרא",
        125L to "סנהדרין",
        126L to "מכות",
        127L to "שבועות",
        128L to "עבודה זרה",
        129L to "הוריות",
        130L to "זבחים",
        131L to "מנחות",
        132L to "חולין",
        133L to "בכורות",
        134L to "ערכין",
        135L to "תמורה",
        136L to "כריתות",
        137L to "מעילה",
        138L to "תמיד",
        139L to "נדה",
        140L to "תלמוד ירושלמי ברכות",
        141L to "תלמוד ירושלמי פאה",
        142L to "תלמוד ירושלמי דמאי",
        143L to "תלמוד ירושלמי כלאים",
        144L to "תלמוד ירושלמי שביעית",
        145L to "תלמוד ירושלמי תרומות",
        146L to "תלמוד ירושלמי מעשרות",
        147L to "תלמוד ירושלמי מעשר שני",
        148L to "תלמוד ירושלמי חלה",
        149L to "תלמוד ירושלמי ערלה",
        150L to "תלמוד ירושלמי בכורים",
        151L to "תלמוד ירושלמי שבת",
        152L to "תלמוד ירושלמי עירובין",
        153L to "תלמוד ירושלמי פסחים",
        154L to "תלמוד ירושלמי שקלים",
        155L to "תלמוד ירושלמי יומא",
        156L to "תלמוד ירושלמי סוכה",
        157L to "תלמוד ירושלמי ביצה",
        158L to "תלמוד ירושלמי ראש השנה",
        159L to "תלמוד ירושלמי תענית",
        160L to "תלמוד ירושלמי מגילה",
        161L to "תלמוד ירושלמי מועד קטן",
        162L to "תלמוד ירושלמי חגיגה",
        163L to "תלמוד ירושלמי יבמות",
        164L to "תלמוד ירושלמי כתובות",
        165L to "תלמוד ירושלמי נדרים",
        166L to "תלמוד ירושלמי נזיר",
        167L to "תלמוד ירושלמי סוטה",
        168L to "תלמוד ירושלמי גיטין",
        169L to "תלמוד ירושלמי קידושין",
        170L to "תלמוד ירושלמי בבא קמא",
        171L to "תלמוד ירושלמי בבא מציעא",
        172L to "תלמוד ירושלמי בבא בתרא",
        173L to "תלמוד ירושלמי סנהדרין",
        174L to "תלמוד ירושלמי מכות",
        175L to "תלמוד ירושלמי שבועות",
        176L to "תלמוד ירושלמי עבודה זרה",
        177L to "תלמוד ירושלמי הוריות",
        178L to "תלמוד ירושלמי נדה",
        411L to "שולחן ערוך, אורח חיים",
        412L to "שולחן ערוך, יורה דעה",
        413L to "שולחן ערוך, אבן העזר",
        414L to "שולחן ערוך, חושן משפט",
      )

  public val CATEGORY_TITLES: Map<Long, String> = mapOf(
        2L to "תורה",
        3L to "נביאים",
        4L to "כתובים",
        5L to "משנה",
        6L to "סדר זרעים",
        7L to "סדר מועד",
        8L to "סדר נשים",
        9L to "סדר נזיקין",
        10L to "סדר קדשים",
        11L to "סדר טהרות",
        12L to "תלמוד בבלי",
        13L to "סדר זרעים",
        14L to "סדר מועד",
        15L to "סדר נשים",
        16L to "סדר נזיקין",
        17L to "סדר קדשים",
        18L to "סדר טהרות",
        19L to "תלמוד ירושלמי",
        20L to "סדר זרעים",
        21L to "סדר מועד",
        22L to "סדר נשים",
        23L to "סדר נזיקין",
        24L to "סדר טהרות",
        60L to "שולחן ערוך",
      )

  public val CATEGORY_BOOKS: Map<Long, List<BookRef>> = mapOf(
        2L to listOf(BookRef(1L, "בראשית"), BookRef(2L, "שמות"), BookRef(3L, "ויקרא"), BookRef(4L,
          "במדבר"), BookRef(5L, "דברים")) ,
        3L to listOf(BookRef(6L, "יהושע"), BookRef(7L, "שופטים"), BookRef(8L, "שמואל א"),
          BookRef(9L, "שמואל ב"), BookRef(10L, "מלכים א"), BookRef(11L, "מלכים ב"), BookRef(12L,
          "ישעיהו"), BookRef(13L, "ירמיהו"), BookRef(14L, "יחזקאל"), BookRef(15L, "הושע"),
          BookRef(16L, "יואל"), BookRef(17L, "עמוס"), BookRef(18L, "עובדיה"), BookRef(19L, "יונה"),
          BookRef(20L, "מיכה"), BookRef(21L, "נחום"), BookRef(22L, "חבקוק"), BookRef(23L, "צפניה"),
          BookRef(24L, "חגי"), BookRef(25L, "זכריה"), BookRef(26L, "מלאכי")) ,
        4L to listOf(BookRef(28L, "תהילים"), BookRef(30L, "משלי"), BookRef(29L, "איוב"),
          BookRef(31L, "שיר השירים"), BookRef(27L, "רות"), BookRef(33L, "איכה"), BookRef(32L,
          "קהלת"), BookRef(34L, "אסתר"), BookRef(35L, "דניאל"), BookRef(36L, "עזרא"), BookRef(37L,
          "נחמיה"), BookRef(38L, "דברי הימים א"), BookRef(39L, "דברי הימים ב")) ,
        5L to listOf() ,
        6L to listOf(BookRef(40L, "משנה ברכות"), BookRef(41L, "משנה פאה"), BookRef(42L,
          "משנה דמאי"), BookRef(43L, "משנה כלאים"), BookRef(44L, "משנה שביעית"), BookRef(45L,
          "משנה תרומות"), BookRef(46L, "משנה מעשרות"), BookRef(47L, "משנה מעשר שני"), BookRef(48L,
          "משנה חלה"), BookRef(49L, "משנה ערלה"), BookRef(50L, "משנה ביכורים")) ,
        7L to listOf(BookRef(51L, "משנה שבת"), BookRef(52L, "משנה עירובין"), BookRef(53L,
          "משנה פסחים"), BookRef(54L, "משנה שקלים"), BookRef(55L, "משנה יומא"), BookRef(56L,
          "משנה סוכה"), BookRef(57L, "משנה ביצה"), BookRef(58L, "משנה ראש השנה"), BookRef(59L,
          "משנה תענית"), BookRef(60L, "משנה מגילה"), BookRef(61L, "משנה מועד קטן"), BookRef(62L,
          "משנה חגיגה")) ,
        8L to listOf(BookRef(63L, "משנה יבמות"), BookRef(64L, "משנה כתובות"), BookRef(65L,
          "משנה נדרים"), BookRef(66L, "משנה נזיר"), BookRef(67L, "משנה סוטה"), BookRef(68L,
          "משנה גיטין"), BookRef(69L, "משנה קידושין")) ,
        9L to listOf(BookRef(70L, "משנה בבא קמא"), BookRef(71L, "משנה בבא מציעא"), BookRef(72L,
          "משנה בבא בתרא"), BookRef(73L, "משנה סנהדרין"), BookRef(74L, "משנה מכות"), BookRef(75L,
          "משנה שבועות"), BookRef(76L, "משנה עדיות"), BookRef(77L, "משנה עבודה זרה"), BookRef(78L,
          "משנה אבות"), BookRef(79L, "משנה הוריות")) ,
        10L to listOf(BookRef(80L, "משנה זבחים"), BookRef(81L, "משנה מנחות"), BookRef(82L,
          "משנה חולין"), BookRef(83L, "משנה בכורות"), BookRef(84L, "משנה ערכין"), BookRef(85L,
          "משנה תמורה"), BookRef(86L, "משנה כריתות"), BookRef(87L, "משנה מעילה"), BookRef(88L,
          "משנה תמיד"), BookRef(89L, "משנה מדות"), BookRef(90L, "משנה קינים")) ,
        11L to listOf(BookRef(91L, "משנה כלים"), BookRef(92L, "משנה אהלות"), BookRef(93L,
          "משנה נגעים"), BookRef(94L, "משנה פרה"), BookRef(95L, "משנה טהרות"), BookRef(96L,
          "משנה מקואות"), BookRef(97L, "משנה נדה"), BookRef(98L, "משנה מכשירין"), BookRef(99L,
          "משנה זבים"), BookRef(100L, "משנה טבול יום"), BookRef(101L, "משנה ידים"), BookRef(102L,
          "משנה עוקצים")) ,
        12L to listOf() ,
        13L to listOf(BookRef(103L, "ברכות")) ,
        14L to listOf(BookRef(104L, "שבת"), BookRef(105L, "עירובין"), BookRef(106L, "פסחים"),
          BookRef(110L, "ראש השנה"), BookRef(107L, "יומא"), BookRef(108L, "סוכה"), BookRef(109L,
          "ביצה"), BookRef(111L, "תענית"), BookRef(112L, "מגילה"), BookRef(113L, "מועד קטן"),
          BookRef(114L, "חגיגה")) ,
        15L to listOf(BookRef(115L, "יבמות"), BookRef(116L, "כתובות"), BookRef(117L, "נדרים"),
          BookRef(118L, "נזיר"), BookRef(119L, "סוטה"), BookRef(120L, "גיטין"), BookRef(121L,
          "קידושין")) ,
        16L to listOf(BookRef(122L, "בבא קמא"), BookRef(123L, "בבא מציעא"), BookRef(124L,
          "בבא בתרא"), BookRef(125L, "סנהדרין"), BookRef(126L, "מכות"), BookRef(127L, "שבועות"),
          BookRef(128L, "עבודה זרה"), BookRef(129L, "הוריות")) ,
        17L to listOf(BookRef(130L, "זבחים"), BookRef(131L, "מנחות"), BookRef(132L, "חולין"),
          BookRef(133L, "בכורות"), BookRef(134L, "ערכין"), BookRef(135L, "תמורה"), BookRef(136L,
          "כריתות"), BookRef(137L, "מעילה"), BookRef(138L, "תמיד")) ,
        18L to listOf(BookRef(139L, "נדה")) ,
        19L to listOf() ,
        20L to listOf(BookRef(140L, "תלמוד ירושלמי ברכות"), BookRef(141L, "תלמוד ירושלמי פאה"),
          BookRef(142L, "תלמוד ירושלמי דמאי"), BookRef(143L, "תלמוד ירושלמי כלאים"), BookRef(144L,
          "תלמוד ירושלמי שביעית"), BookRef(145L, "תלמוד ירושלמי תרומות"), BookRef(146L,
          "תלמוד ירושלמי מעשרות"), BookRef(147L, "תלמוד ירושלמי מעשר שני"), BookRef(148L,
          "תלמוד ירושלמי חלה"), BookRef(149L, "תלמוד ירושלמי ערלה"), BookRef(150L,
          "תלמוד ירושלמי בכורים")) ,
        21L to listOf(BookRef(151L, "תלמוד ירושלמי שבת"), BookRef(152L, "תלמוד ירושלמי עירובין"),
          BookRef(153L, "תלמוד ירושלמי פסחים"), BookRef(155L, "תלמוד ירושלמי יומא"), BookRef(154L,
          "תלמוד ירושלמי שקלים"), BookRef(156L, "תלמוד ירושלמי סוכה"), BookRef(158L,
          "תלמוד ירושלמי ראש השנה"), BookRef(157L, "תלמוד ירושלמי ביצה"), BookRef(159L,
          "תלמוד ירושלמי תענית"), BookRef(160L, "תלמוד ירושלמי מגילה"), BookRef(162L,
          "תלמוד ירושלמי חגיגה"), BookRef(161L, "תלמוד ירושלמי מועד קטן")) ,
        22L to listOf(BookRef(163L, "תלמוד ירושלמי יבמות"), BookRef(167L, "תלמוד ירושלמי סוטה"),
          BookRef(164L, "תלמוד ירושלמי כתובות"), BookRef(165L, "תלמוד ירושלמי נדרים"), BookRef(166L,
          "תלמוד ירושלמי נזיר"), BookRef(168L, "תלמוד ירושלמי גיטין"), BookRef(169L,
          "תלמוד ירושלמי קידושין")) ,
        23L to listOf(BookRef(170L, "תלמוד ירושלמי בבא קמא"), BookRef(171L,
          "תלמוד ירושלמי בבא מציעא"), BookRef(172L, "תלמוד ירושלמי בבא בתרא"), BookRef(173L,
          "תלמוד ירושלמי סנהדרין"), BookRef(175L, "תלמוד ירושלמי שבועות"), BookRef(176L,
          "תלמוד ירושלמי עבודה זרה"), BookRef(174L, "תלמוד ירושלמי מכות"), BookRef(177L,
          "תלמוד ירושלמי הוריות")) ,
        24L to listOf(BookRef(178L, "תלמוד ירושלמי נדה")) ,
        60L to listOf(BookRef(411L, "שולחן ערוך, אורח חיים"), BookRef(412L, "שולחן ערוך, יורה דעה"),
          BookRef(413L, "שולחן ערוך, אבן העזר"), BookRef(414L, "שולחן ערוך, חושן משפט")) ,
      )

  public val TOC_BY_TOC_TEXT_ID: Map<Long, Map<Long, TocQuickLink>> = mapOf(
      )
}
